CREATE SEQUENCE user_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE resource_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE map_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE result_id_seq START WITH 1 INCREMENT BY 1;
